

import java.awt.event.WindowEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Workbook;

/**
 *
 * @author madiyarsharipov
 */
public class History extends javax.swing.JFrame {
    //Library_n user=new Library_n();
    ExcelReader NEWreader = new ExcelReader();
    
    
    public History() throws IOException {
        initComponents();
        setLocationRelativeTo(null);
        Reveal();
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User", "Issue Date", "Return Date", "Title", "Author", "ISBN", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(10);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void Reveal() throws FileNotFoundException, IOException{
        
        FileInputStream fis = new FileInputStream("users.xls");
        
        Workbook wb = (Workbook) new HSSFWorkbook(fis);
             
        int rowcount=wb.getSheetAt(0).getPhysicalNumberOfRows();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        for(int i=0;i<rowcount;i++){
            
                model.addRow(new Object[]{wb.getSheetAt(0).getRow(i).getCell(0).getStringCellValue(),
                                          wb.getSheetAt(0).getRow(i).getCell(1).getStringCellValue(),
                                          wb.getSheetAt(0).getRow(i).getCell(2).getStringCellValue(),
                                          NEWreader.library.get(NEWreader.indeces.indexOf(wb.getSheetAt(0).getRow(i).getCell(3).getStringCellValue())).getTitle(),
                                          NEWreader.library.get(NEWreader.indeces.indexOf(wb.getSheetAt(0).getRow(i).getCell(3).getStringCellValue())).getAuthor(),
                                          wb.getSheetAt(0).getRow(i).getCell(3).getStringCellValue(),  
                                          NEWreader.library.get(NEWreader.indeces.indexOf(wb.getSheetAt(0).getRow(i).getCell(3).getStringCellValue())).getStock(),
                
                });
         
            }
        }
        
        
        
    
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new History().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(History.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
